version: '3'

services:

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: schedule
    ports:
      - "5432:5432"
    #volumes:
     # - ./postgres:/var/lib/postgresql/data
    
    networks:
      - web
      
networks:
  web:
    driver: bridge